# Generated by Django 6.0.6 on 2026-06-11 06:01

import core.utils
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kindergarten'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', "Bog'cha Admini"), ('staff', 'Xodim'), ('parent', 'Ota-ona'), ('superadmin', 'Tizim Admini')], default='parent', max_length=20),
        ),
        migrations.CreateModel(
            name='KindergartenAdminProfile',
            fields=[
                ('id', models.CharField(default=core.utils.generate_custom_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='core.kindergarten')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ParentProfile',
            fields=[
                ('id', models.CharField(default=core.utils.generate_custom_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parents', to='core.kindergarten')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.CharField(default=core.utils.generate_custom_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lavozimi')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff', to='core.kindergarten')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='staff_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
