# Generated by Django 6.0.6 on 2026-06-11 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
        ('groups', '0001_initial'),
        ('users', '0002_alter_user_role_kindergartenadminprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parentprofile',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='child',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_profiles', to='children.child'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_profiles', to='groups.group'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ismi'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='passport_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='passport_seria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Familiyasi'),
        ),
        migrations.AddField(
            model_name='parentprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
