# Generated by Django 6.0.4 on 2026-06-11 07:34

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kindergarten'),
        ('groups', '0002_camera'),
        ('users', '0003_parentprofile_birth_day_parentprofile_child_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffprofile',
            name='position',
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='birth_day',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='camera_image',
            field=models.ImageField(blank=True, null=True, upload_to='staff/camera/'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='staff_profiles', to='groups.group'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='staff/images/'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Ismi'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='passport_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='passport_seria',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='surname',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Familiyasi'),
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='KindergartenRole',
            fields=[
                ('id', models.CharField(default=core.utils.generate_custom_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Rol nomi')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='core.kindergarten')),
            ],
        ),
        migrations.AddField(
            model_name='staffprofile',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profiles', to='users.kindergartenrole'),
        ),
    ]
