# Generated by Django 6.0.6 on 2026-06-11 05:18

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KindergartenApplication',
            fields=[
                ('id', models.CharField(default=core.utils.generate_custom_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name="Bog'cha nomi")),
                ('region', models.CharField(max_length=80, verbose_name='Viloyat')),
                ('district', models.CharField(max_length=80, verbose_name='Tuman / Shahar')),
                ('address', models.TextField(blank=True, default='', max_length=300, verbose_name="To'liq manzil")),
                ('phone', models.CharField(max_length=20, verbose_name='Telefon raqam')),
                ('status', models.CharField(choices=[('pending', '⏳ Kutilmoqda'), ('active', '✅ Faol'), ('inactive', '❌ Nofaol')], db_index=True, default='pending', max_length=10, verbose_name='Holat')),
                ('applied_at', models.DateTimeField(auto_now_add=True, verbose_name='Ariza vaqti')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': "Bog'cha arizasi",
                'verbose_name_plural': "Bog'cha arizalari",
                'ordering': ['-applied_at'],
            },
        ),
    ]
