# Generated by Django 6.0.6 on 2026-06-11 06:01

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('id', models.CharField(default=core.utils.generate_custom_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name="Bog'cha nomi")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol holatda')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': "Bog'cha",
                'verbose_name_plural': "Bog'chalar",
                'ordering': ['-created_at'],
            },
        ),
    ]
