# Generated by Django 6.0.6 on 2026-06-11 06:36

import core.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.CharField(default=core.utils.generate_custom_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Ismi')),
                ('surname', models.CharField(max_length=150, verbose_name='Familiyasi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='children/images/')),
                ('camera_image', models.ImageField(blank=True, null=True, upload_to='children/camera/')),
                ('metrka_id', models.CharField(blank=True, max_length=50, null=True)),
                ('metrka_seria', models.CharField(blank=True, max_length=50, null=True)),
                ('birth_day', models.DateField(blank=True, null=True)),
                ('kasallik_tarixi', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
