# Generated by Django 6.0.6 on 2026-06-11 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('children', '0001_initial'),
        ('core', '0002_kindergarten'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='groups.group'),
        ),
        migrations.AddField(
            model_name='child',
            name='kindergarten',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.kindergarten'),
        ),
    ]
