# Generated by Django 6.0.6 on 2026-06-11 06:36

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_kindergarten'),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.CharField(default=core.utils.generate_custom_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150, verbose_name='Guruh nomi')),
                ('image', models.ImageField(blank=True, null=True, upload_to='groups/', verbose_name='Rasm')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='core.kindergarten')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
