# Generated by Django 6.0.4 on 2026-06-11 07:06

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_kindergarten'),
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.CharField(default=core.utils.generate_custom_id, editable=False, max_length=64, primary_key=True, serialize=False)),
                ('kamera_nomi', models.CharField(max_length=150, verbose_name='Kamera nomi')),
                ('kamera_url', models.URLField(max_length=500, verbose_name='Kamera URL manzili')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='groups.group')),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='core.kindergarten')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
